name: Document Export

on: [push]

jobs:
  Generate-Checklists:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Listing repo recursive
      run: ls -lR
    
    - name: Get Latest MASVS Release Tag
      id: latestrelease
      run: |
        echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/OWASP/owasp-masvs/releases/latest | jq '.tag_name' | sed 's/\"//g')"

    - name: Confirm MASVS Release Tag
      run: |
        echo ${{ steps.latestrelease.outputs.releasetag }}

    - uses: actions/checkout@v2
      with:
        repository: "OWASP/owasp-masvs.git"
        ref: "${{ steps.latestrelease.outputs.releasetag }}"
        fetch-depth: 1
        path: tools/scripts/owasp-masvs

    - name: Listing of scripts directory
      run: ls -l tools/scripts/

    - name: Install pip Requirements
      run: pip3 install -r tools/scripts/requirements.txt

    - name: Convert MSTG Testing Chapters to HTML
      run: . tools/scripts/mstg_to_html.sh

    - name: List MSTG HTML
      run: ls -l tools/scripts/generated/html/

    - name: Export YAML, enhance with MSTG and generate Excel
      run: cd tools/scripts && ./gen_all_excel.sh

    - name: Upload MASVS YAML
      uses: actions/upload-artifact@v2
      with:
        name: MASVS YAML Files
        path: tools/scripts/masvs_*.yaml

    - name: Upload Enhanced MASVS YAML
      uses: actions/upload-artifact@v2
      with:
        name: Enhanced MASVS YAML Files
        path: tools/scripts/masvs_full_*.yaml

    - name: Upload Checklists
      uses: actions/upload-artifact@v2
      with:
        name: Checklists
        path: tools/scripts/checklist_*.xlsx